# Generated by Django 3.0.8 on 2020-07-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imange',
            new_name='image',
        ),
    ]
